services:
  app:
    image: ghcr.io/fccview/rwmarkable:main
    container_name: rwmarkable
    user: "1001:65533"
    ports:
      - "1234:3000"
    volumes:
      - ./data:/app/data:rw # Do NOT change this volume name.
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HTTPS=false
    init: true
