version: "3.8"

services:
  app:
    image: ghcr.io/riofriz/rwmarkable:latest
    container_name: rwmarkable
    ports:
      - "3000:3000"
    volumes:
      - rwmarkable_data:/app/data
    restart: unless-stopped

volumes:
  rwmarkable_data:
