services:
  app:
    image: ghcr.io/riofriz/rwMarkable:latest
    container_name: rwMarkable
    ports:
      - "1234:3000"
    volumes:
      - rwmarkable_data:/app/data
    restart: unless-stopped

volumes:
  rwmarkable_data:
