name: Create Manifest (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Base tag to create manifest for (e.g., latest)"
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          tag="ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}"
          echo "Creating manifest for ${tag}"
          docker buildx imagetools create --tag "${tag}" \
            "${tag}-amd64" \
            "${tag}-arm64"
