name: Create Multi-Platform Manifests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create manifests for"
        required: true
        default: "latest"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest for specified tag
        run: |
          tag="${{ github.event.inputs.tag }}"

          echo "Creating manifest for tag: ${tag}"

          # Check if both platform-specific images exist
          if docker buildx imagetools inspect "${tag}-amd64" >/dev/null 2>&1 && docker buildx imagetools inspect "${tag}-arm64" >/dev/null 2>&1; then
            echo "✅ Both platform images exist for ${tag}, creating manifest"
            docker buildx imagetools create --tag "${tag}" \
              "${tag}-amd64" \
              "${tag}-arm64"
            echo "✅ Manifest created successfully for ${tag}"
          else
            echo "❌ Cannot create manifest - missing platform images"
            echo "AMD64 image exists: $(docker buildx imagetools inspect "${tag}-amd64" >/dev/null 2>&1 && echo 'YES' || echo 'NO')"
            echo "ARM64 image exists: $(docker buildx imagetools inspect "${tag}-arm64" >/dev/null 2>&1 && echo 'YES' || echo 'NO')"
            exit 1
          fi
