name: Docker Build

on:
  workflow_call:
    inputs:
      platform:
        description: "The platform to build for (e.g., linux/amd64)"
        required: true
        type: string
      suffix:
        description: "The suffix to add to the tags (e.g., -amd64)"
        required: true
        type: string
    secrets:
      token:
        description: "GitHub token with packages:write permission"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=${{ inputs.suffix }}
            type=ref,event=pr,suffix=${{ inputs.suffix }}
            type=ref,event=tag,suffix=${{ inputs.suffix }}
            type=semver,pattern={{version}},suffix=${{ inputs.suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ inputs.suffix }}
            type=sha,suffix=${{ inputs.suffix }}
            type=raw,value=latest,suffix=${{ inputs.suffix }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
