name: Docker Publish

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-amd64:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/amd64
      suffix: -amd64
    permissions:
      contents: read
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-arm64:
    runs-on: ubuntu-22.04-arm
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/arm64
      suffix: -arm64
    permissions:
      contents: read
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for manifest
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest

      - name: Create and push manifest
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            echo "Creating manifest for tag: ${tag}"

            # Check if both platform-specific images exist before creating manifest
            if docker buildx imagetools inspect "${tag}-amd64" && docker buildx imagetools inspect "${tag}-arm64"; then
              echo "Both platform images exist for ${tag}, creating manifest"
              docker buildx imagetools create --tag "${tag}" \
                "${tag}-amd64" \
                "${tag}-arm64"
            else
              echo "Warning: One or both platform images missing for ${tag}, skipping manifest creation"
            fi
          done
