name: Publish Docker AMD64

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/amd64
      suffix: -amd64
      runner: ubuntu-latest
    permissions:
      contents: read
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}