name: Reusable ARM64 Build

on:
  workflow_call:
    secrets:
      token: { required: true }

jobs:
  call-build-workflow:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/arm64
      suffix: -arm64
      runner: ubuntu-latest-arm64
    secrets:
      token: ${{ secrets.token }}