name: Reusable AMD64 Build

on:
  workflow_call:
    secrets:
      token: { required: true }

jobs:
  call-build-workflow:
    uses: ./.github/workflows/docker-build.yml
    with:
      platform: linux/amd64
      suffix: -amd64
      runner: ubuntu-latest
    secrets:
      token: ${{ secrets.token }}